version: "3.7"

services:
  
  search-api:
    build: 
      context: ./search-api
      # Uncomment if testing against a specific branch of commons other than the PyPI package
      # Will also need to use the 'git+https://github.com/hubmapconsortium/commons.git@${COMMONS_BRANCH}#egg=hubmap-commons'
      # in src/requirements.txt accordingly
      # args:
      #   # The commons github branch to be used during image build (default to master if not set or null)
      #   - COMMONS_BRANCH=${COMMONS_BRANCH:-master}
    # Build the image with name and tag
    # Exit with an error message containing err if unset or empty in the environment
    image: hubmap/search-api:${SEARCH_API_VERSION:?err}
    volumes:  
      # Mount the VERSION file and BUILD file 
      - "../VERSION:/usr/src/app/VERSION" 
      - "../BUILD:/usr/src/app/BUILD" 
      # Mount the source code to container  
      - "../src:/usr/src/app/src"
